version: '3.5'

services:

  node-a:
    container_name: node-a
    hostname: node-a
    image: cockroachdb/cockroach:v2.1.5
    command: start --logtostderr --insecure --locality=region=A

  node-b:
    container_name: node-b
    hostname: node-b
    image: cockroachdb/cockroach:v2.1.5
    command: start --logtostderr --insecure --locality=region=B --join=node-a
    depends_on:
      - node-a

  node-c:
    container_name: node-c
    hostname: node-c
    image: cockroachdb/cockroach:v2.1.5
    command: start --logtostderr --insecure --locality=region=C --join=node-a
    depends_on:
      - node-a

  node-d:
    container_name: node-d
    hostname: node-d
    image: cockroachdb/cockroach:v2.1.5
    command: start --logtostderr --insecure --locality=region=D --join=node-a
    depends_on:
      - node-a

  node-e:
    container_name: node-e
    hostname: node-e
    image: cockroachdb/cockroach:v2.1.5
    command: start --logtostderr --insecure --locality=region=E --join=node-a
    depends_on:
      - node-a

  node-f:
    container_name: node-f
    hostname: node-f
    image: cockroachdb/cockroach:v2.1.5
    command: start --logtostderr --insecure --locality=region=F --join=node-a
    depends_on:
      - node-a


  lb:
    container_name: lb
    hostname: lb
    build: haproxy
    ports:
      - "5432:5432"
      - "8080:8080"
      - "8081:8081"
    links:
      - node-a
      - node-b
      - node-c
      - node-d
      - node-e
      - node-f

  prometheus:
    container_name: prometheus
    hostname: prometheus
    build: ./prometheus
    ports:
      - "9090:9090"
    depends_on:
      - lb

  grafana:
    container_name: grafana
    hostname: grafana
    build: ./grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus