version: '3.5'

services:

  gcp-east:
    container_name: gcp-east
    hostname: gcp-east
    image: cockroachdb/cockroach:v2.1.5
    command: start --logtostderr --insecure --locality=region=gcp-east

  azure-east:
    container_name: azure-east
    hostname: azure-east
    image: cockroachdb/cockroach:v2.1.5
    command: start --logtostderr --insecure --locality=region=azure-east --join=gcp-east
    depends_on:
      - gcp-east

  gcp-central:
    container_name: gcp-central
    hostname: gcp-central
    image: cockroachdb/cockroach:v2.1.5
    command: start --logtostderr --insecure --locality=region=gcp-central --join=gcp-east
    depends_on:
      - gcp-east

  gcp-west:
    container_name: gcp-west
    hostname: gcp-west
    image: cockroachdb/cockroach:v2.1.5
    command: start --logtostderr --insecure --locality=region=gcp-west --join=gcp-east
    depends_on:
      - gcp-east

  azure-west:
    container_name: azure-west
    hostname: azure-west
    image: cockroachdb/cockroach:v2.1.5
    command: start --logtostderr --insecure --locality=region=azure-west --join=gcp-east
    depends_on:
      - gcp-east


  lb:
    container_name: lb
    hostname: lb
    build: haproxy
    ports:
      - "5432:5432"
      - "8080:8080"
      - "8081:8081"
    links:
      - gcp-east
      - azure-east
      - gcp-central
      - gcp-west
      - azure-west

  prometheus:
    container_name: prometheus
    hostname: prometheus
    build: ./prometheus
    ports:
      - "9090:9090"
    depends_on:
      - lb

  grafana:
    container_name: grafana
    hostname: grafana
    build: ./grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus