version: '3.5'

networks:
  crdb-net:
    driver: bridge

services:

  crdb-1:
    container_name: crdb-1
    hostname: crdb-1
    image: cockroachdb/cockroach:latest
    networks:
      - crdb-net
    ports:
      - "8080:8080"
    command: start --logtostderr --insecure

  crdb-2:
    container_name: crdb-2
    hostname: crdb-2
    image: cockroachdb/cockroach:latest
    networks:
      - crdb-net
    command: start --logtostderr --insecure --join=crdb-1
    depends_on:
      - crdb-1

  crdb-3:
    container_name: crdb-3
    hostname: crdb-3
    image: cockroachdb/cockroach:latest
    networks:
      - crdb-net
    command: start --logtostderr --insecure --join=crdb-1
    depends_on:
      - crdb-1

  prometheus:
    container_name: prometheus
    hostname: prometheus
    build: ./prometheus
    networks:
      - crdb-net
    ports:
      - "9090:9090"

  lb:
    container_name: lb
    hostname: lb
    build: haproxy
    networks:
      - crdb-net
    ports:
      - "5432:5432"
      - "8081:8081"
    links:
      - crdb-1
      - crdb-2
      - crdb-3