{
 "title": "Store Demo",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Available Balance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(runner_available_balance_seconds_bucket[10s]))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.75, rate(runner_available_balance_seconds_bucket[10s]))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.95, rate(runner_available_balance_seconds_bucket[10s]))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, rate(runner_available_balance_seconds_bucket[10s]))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Create Authorization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(runner_create_auth_seconds_bucket[10s]))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.75, rate(runner_create_auth_seconds_bucket[10s]))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.95, rate(runner_create_auth_seconds_bucket[10s]))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, rate(runner_create_auth_seconds_bucket[10s]))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Update Authorization and Account",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(runner_update_records_seconds_bucket[10s])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(runner_update_records_seconds_bucket[10s])) by (le))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(runner_update_records_seconds_bucket[10s])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(runner_update_records_seconds_bucket[10s])) by (le))",
     "legendFormat": "P99"
    }
   ]
  }
 ]
}