CREATE TABLE ACCT (
  ACCT_NBR         STRING(25)     NOT NULL,
  ACCT_TYPE_IND    CHAR(2)        NOT NULL,
  ACCT_BAL_AMT     DECIMAL(18, 4) NOT NULL,
  ACCT_STAT_CD     DECIMAL(2, 0)  NOT NULL,
  EXPIR_DT         DATE      DEFAULT NULL,
  CRT_TS           TIMESTAMP      NOT NULL,
  LAST_UPD_TS      TIMESTAMP DEFAULT NULL,
  LAST_UPD_USER_ID STRING(8) DEFAULT NULL,
  ACTVT_INQ_TS     TIMESTAMP DEFAULT NULL,
  STATE            STRING(2)      NOT NULL,
  PRIMARY KEY (STATE ASC, ACCT_NBR ASC))
  PARTITION BY LIST (STATE) (
    PARTITION east VALUES IN ('SC'),
    PARTITION central VALUES IN ('TX'),
    PARTITION west VALUES IN ('CA'));