DROP TABLE IF EXISTS ACCT CASCADE;

CREATE TABLE IF NOT EXISTS ACCT
(
  ACCT_NBR         STRING(25)     NOT NULL,
  ACCT_TYPE_IND    CHAR(2)        NOT NULL,
  ACCT_BAL_AMT     DECIMAL(18, 4) NOT NULL,
  ACCT_STAT_CD     DECIMAL(2, 0)  NOT NULL,
  EXPIR_DT         DATE      DEFAULT NULL,
  CRT_TS           TIMESTAMP      NOT NULL,
  LAST_UPD_TS      TIMESTAMP DEFAULT NULL,
  LAST_UPD_USER_ID STRING(8) DEFAULT NULL,
  ACTVT_INQ_TS     TIMESTAMP DEFAULT NULL,
  STATE            STRING(2)      NOT NULL,
  PRIMARY KEY (ACCT_NBR)
);

DROP TABLE IF EXISTS AUTH CASCADE;

CREATE TABLE IF NOT EXISTS AUTH
(
  ACCT_NBR         STRING(25)     NOT NULL,
  REQUEST_ID       UUID           NOT NULL,
  AUTH_ID          STRING(64)     NOT NULL,
  AUTH_AMT         DECIMAL(18, 4) NOT NULL,
  AUTH_STAT_CD     DECIMAL(2, 0)  NOT NULL,
  CRT_TS           TIMESTAMP      NOT NULL,
  LAST_UPD_TS      TIMESTAMP      NOT NULL,
  LAST_UPD_USER_ID STRING(8)      NOT NULL,
  STATE            STRING(2)      NOT NULL,
  PRIMARY KEY (ACCT_NBR, REQUEST_ID)
);