global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - "aggregation.rules.yml"

scrape_configs:

  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8082']

  - job_name: 'cockroachdb'
    metrics_path: '/_status/vars'
    static_configs:
      - targets: ['node-a:8080', 'node-b:8080', 'node-c:8080', 'node-d:8080', 'node-e:8080', 'node-f:8080']